import { Inter } from 'next/font/google'
import Link from 'next/link';
import './globals.scss'
import './header.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <Link id="logo-container" href="/">
            <img id="logo" src='https://trnkt-dev.s3.amazonaws.com/Logo_Small.png'/>
            FreeSA
          </Link>
          <h1>Header</h1>
          <span>Hamburger Icon</span>
        </header>
        {children}
      </body>
    </html>
  )
}
